### ISSUE TITLE
Eyyy lmao

### ISSUE THREAD

**Issue by birdbrainswagtrain** [wiox/gmod-keypad#12]

**Comment by Authorjames** [comment]
problem?

**Comment by Authorjames** [comment]
＿_,,,,、 .,、
　　　　　　　　　　 　／'ﾞ´,_/'″　 . ｀＼
　　　　　　　　　 : ./ 　　i./　,,..、　　　 ヽ
　　　　　　　　 . /　　　 /．　ｌ, ,!　　　　 ｀,
　 　 　 　 　 　.| 　.,..‐.､│　 　 　　　　 　.|
　 　 　 　 　 　（´゛ ,/　llヽ 　　 　 　 　 　 |
　　　 　 　 　 　 ヽ -./ .， lliヽ　　　　　　 .|
　　 　 　 　 　 　 /'",i" ﾞ;、 ｌ'ｉi,''く　　　　　.ヽ
　　　　　　　　　/ ...│　 ﾞl,　 ｌﾞﾞt, ''ii_　　　　:.!
　　　　　　　 : /.._　/ 　 　ヽ　＼＼.｀ﾞ~''''''"./
　　　　　　　 .|-ﾞノ/　　 : ゝ　.､　` .｀''←┬゛
　 　 　 　 　 lﾞ　/.ｒ　　　゛ .ﾞﾋ, .ヽ,　　￣ﾞ|
　　　　　　 . | ./ ｌ　　　　　　”'､ .ﾞゝ........ん
　　　　　　　l　 /　　　　 ヽ　.`' ｀､、 　.,i゛
　　　　　　 .l|　 !　　　 ''''v,　　　 ﾞ''ｰ　．l、
　　　　　　 |lﾞ .il、　　.l　　.ヽ　 .¬---イ
　　　　　　.llﾞ, ./ 　　 !　 　 　 　 　 　 ,!
　　　　　　.!!...!!　　　,,ﾞ''''ｰ　　　　　　 .|
　　　　　　l.",!　　　 .ﾘ　　　　　　　　 |
　　　　　　l":|　　　 .〜'''　　　　 　,. │
　　　　　　l; :!　　　 .|'"　　 　...ノ,ﾞ./ │
　　　　　　l: l｢　　　 !　　　 .￣ﾞﾞ /　　!
　　　　　 .| .|　　　　!　　　　　,i│　　|
　　　　　 :! .l.　　　 ｝　　　　,i'./ 　　 |
　　　　　 :! .|　　　 :|　　　 . / 　　　 .|
　　　　　 :! |　　　 ;!　　　"　　　　 　.|
　　　　　 :! !　　　 │　　　　　　　　│
　　　　　 :!:|　　 　 　 　 　 　 　 ,! i　,!
　　　　　 :! ，　　　 .ｌ,　　　　　 / .lﾞ　!
　　　　　 :! |　　　 ， ｌ.　　　　　| .|　　:，
　　　 : v'" .!　　　 |'i .ヽ,　　　 ./ :!　　.ヽ
　_,　_/　　/ 　　　　.ｌ　　゛　._/　:lﾞ　　　 .｀ﾞ"
