### ISSUE TITLE
2 Reports

### ISSUE THREAD

**Issue by deinemudda32** [wiox/gmod-keypad#6]
I really love the Keypad addon and I'd like to report 2 mistakes/bugs or whatever fuck to probably improve the awesomeness of it.

So first on my DarkRP Servers some players are getting random errors from the addon sometimes.
I deleted it suddenly but something with KeyPadData is invalid. Nvm.

So 2nd real mistake is to whatever you setup the convar of the keypad cracktime its always 30 seconds,
Tested on 2 servers.

**Comment by wiox** [comment]
> So first on my DarkRP Servers some players are getting random errors from the addon sometimes.
> I deleted it suddenly but something with KeyPadData is invalid. Nvm.

I'll need the exact error message and - if possible - how to cause it.



> So 2nd real mistake is to whatever you setup the convar of the keypad cracktime its always 30 seconds,
> Tested on 2 servers.

You must set the value of the ConVar before the cracker is spawned.

**Comment by deinemudda32** [comment]
1. Sorry I dont know how to reproduce, but I m keeping an eye open.

2. If I set the value to we say 15, the interface which shows "Cracking" is running to the half of the bar and then completed.

**Comment by deinemudda32** [comment]
[ERROR] addons/tools/lua/weapons/gmod_tool/stools/keypad_willox.lua:87: attempt to index field 'KeypadData' (a nil value)
  1. RightClick - addons/tools/lua/weapons/gmod_tool/stools/keypad_willox.lua:87
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:281

got it

**Comment by deinemudda32** [comment]
Since the gmod update, the error appears 20 times a log.
